pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
    actions:
      merge:
        method: merge
      review:
        type: APPROVE
        message: Automatically approving dependabot
