name: Build&Dockerize
on:
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:
    branches: [ main ]
env:
  IMAGE_NAME: netcoreboilerplate
  ConnectionStrings__BoilerplateConnectionString: "Host=localhost;Database=testdb;Username=postgres;Password=postgres"

jobs:
  build:
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:13-alpine
        ports:
          - 5432:5432
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000
          - 10001:10001
          - 10002:10002
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        dotnet-quality: 'preview'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Migrate DB
      run: |
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        dotnet ef database update --startup-project BervProject.WebApi.Boilerplate --project BervProject.WebApi.Boilerplate
    - name: Test
      run: dotnet test --configuration Release --no-restore --no-build --verbosity normal --collect:"XPlat Code Coverage"
    - name: Report Codecov
      uses: codecov/codecov-action@v3
  build-docker-test:
    runs-on: ubuntu-22.04
    if: github.event_name == 'pull_request'
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Build Image
        run: docker build . -t $IMAGE_NAME
      - name: Install Docker Scan Plugin
        run: sudo apt-get update && sudo apt-get install -y docker-scan-plugin
      - name: Check Scan Version
        run: docker scan --accept-license --version
      - name: Scan Image
        run: docker scan $IMAGE_NAME
  build-push-docker:
    runs-on: ubuntu-22.04
    if: github.event_name == 'push'
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          bervproject/${{ env.IMAGE_NAME }}
          ghcr.io/${{ github.repository }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
